### ISSUE TITLE
SSH Tunnel Support

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-db2-deprecated#5]
Options: 

1) add ssh tunnel support
2) remove ssh portion from UI for this extractor

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/27078563-56e28204-5034-11e7-86e0-d1b04a42fcc9.png)

**Comment by pivnicek** [comment]
I'll work on that ^

**Comment by pivnicek** [comment]
not quite there yet 
![image](https://user-images.githubusercontent.com/569139/27085967-109fedfa-5051-11e7-85d7-7a48846fe98c.png)

**Comment by pivnicek** [comment]
all better:)
